services:
  backend:
    build:
      context: backend
    container_name: backend
    depends_on:
      - database
      - mqtt-broker
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8080"
    restart: unless-stopped

  database:
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USERNAME=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    image: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql

  modpoll:
    command: >
      modpoll
        --config /app/config/vmi9.csv
        --daemon
        --mqtt-host mqtt-broker
        --mqtt-port 1883
        --mqtt-publish-topic-pattern {{device_name}}
        --mqtt-qos 0
        --mqtt-version 5.0
        --rate ${MODPOLL_RATE_S}
        --tcp ${HEAT_PUMP_IP}
        --tcp-port ${HEAT_PUMP_PORT}
        --timestamp
    container_name: modpoll
    depends_on:
      - mqtt-broker
    env_file:
      - .env
    image: topmaker/modpoll
    restart: unless-stopped
    volumes:
      - ./modpoll/vmi9.csv:/app/config/vmi9.csv

  mqtt-broker:
    container_name: emqx
    env_file:
      - .env
    environment:
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DASHBOARD_DEFAULT_PASSWORD}
      - EMQX_DASHBOARD__DEFAULT_USERNAME=${EMQX_DASHBOARD_DEFAULT_USERNAME}
    image: emqx
    ports:
      - "${MQTT_BROKER_PORT}:1883"
      - "${MQTT_BROKER_TLS_PORT}:8083"
      - "${EMQX_DASHBOARD_PORT}:18083"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  ui:
    build:
      context: ui
    container_name: ui
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "${UI_PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env

volumes:
  pgadmin_data:
  postgres_data:
