spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD:postgres}
    url: jdbc:postgresql://${DATABASE_ADDRESS:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
