name: Terrace Heating

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: "Prepare environment for validation"
        run: "cp .env.example .env"
      - name: "Validate Docker Compose File"
        run: "docker compose config"
      - name: "Build images"
        run: "docker compose build"
